apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: observability
type: Opaque
stringData:
  admin-user: CHANGE_ME
  admin-password: CHANGE_ME
