server:
  nodeSelector:
    topology.k3s.io/role: metrics
  tolerations:
    - key: dedicated
      operator: Equal
      value: metrics
      effect: NoSchedule

alertmanager:
  enabled: false

extraScrapeConfigs: []
