tempo:
  nodeSelector:
    topology.k3s.io/role: logs-traces
  tolerations:
    - key: dedicated
      operator: Equal
      value: logs-traces
      effect: NoSchedule

  storage:
    trace:
      backend: local
